
services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - 3tier_bridge
    depends_on:
      - tomcat

  tomcat:
    build: ./tomcat
    container_name: tomcat
    environment:
      - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom
    networks:
      - 3tier_bridge
    depends_on:
      - mysql
    volumes:
      - ./tomcat/webapp:/usr/local/tomcat/webapps/ROOT

  mysql:
    build: ./mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - 3tier_bridge

volumes:
  mysql_data:

networks:
  3tier_bridge:
    driver: bridge

